### PR TITLE
Add max aggregation for CPU in VM details

### PR DESCRIPTION
**Pull request by BernieWhite**
## PR Checklist

Currently the VM details workbook includes a metric for Percent CPU using the _avg_ aggregation. When checking the performance of VMs it is often helpful to understand what the _max_ of a datapoint is. For example if the granularity is 8 hours, an average could quite different then as represented by a 5 minute granularity.

This PR:

- Updates the existing workbook to add a max metric aggregation.
- Removes the hardcoded theme to default to auto since there is two metrics displayed instead of one.

### CODE REVIEW

**Comment by BernieWhite** [comment]
@nasundar Bump.

**Comment by BernieWhite** [comment]
@nasundar @microsoft/applicationinsights-devtools Is there anything else that I need to do here to get this merged?

**Comment by yves-chan** [comment]
@BernieWhite, Can you include some screenshots for before and after? We need to check with the authors of this workbook to ensure this change makes sense on a template level.

@nasundar @rakshith210 Can you review?

**Comment by nasundar** [comment]
@BernieWhite sorry, I missed this PR and thanks @yves-chan for reminding me.
BTW, I am not the author of this workbook, looks like its @acearun. I have added Arun as reviewer as well.
The change looks pretty straight forward, and it makes sense to view "Max" for CPU. So, I will approve this PR. 

Thinking about this workbook more holistically, it might be better to provide a dropdown with supported aggregates so that user can pick the aggregates that suits their scenario, something similar to below. But this requires a separate discussion. 
image

**Review by nasundar — APPROVED** [review]

**Review by raghavthind2005 — APPROVED** [review]

**Pull request merged**
