### PR TITLE
Added VM metrics, VM health, and VM Health Changes tiles to ACSS_Aggregated and SAP_Inventory_Checks workbooks.

### PR DESCRIPTION
**Pull request by adityashukla-msft**
### Added the following tiles to the ACSS_Aggregated workbook:
- **VM Monitoring Metrics (Last 24 hours):**

Shows the list of VMs for the selected VIS(es), and their health metrics in the past 24 hours.

image

image

Since this is a metrics tile which gets the metrics for VMs, I had to find a workaround to add a column for the SID of the VMs. To do that I had to create 2 hidden steps, and then create a 3rd query step in which I'm getting the data by merging the results of the previous 2 steps.

- **Current VM Health & Annotations:**

Shows the list of VMs for the selected VIS(es), and their current health and annotations.

image

- **VM Health Changes (Last 14 days):**

Shows the list of VMs for the selected VIS(es), and their corresponding health changes in the past 14 days.

I also had to add a parameter **vmIds** to the ACSS_Aggregated workbook, as I had to supply that column to get the metrics for the VMs. The existing vmList parameter is a list of comma separated visIds and vmIds.

### Added the same tiles to the SAP_Inventory_Checks workbook:

**Link to try out changes:** https://ms.portal.azure.com/?feature.workbookGalleryRedirect=https%3A%2F%2Fworkbookpoctemplates.blob.core.windows.net%2Facss-workbook-templates%2Fpackage#home

## PR Checklist

* [x] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [x] Validate your changes using one or more of the [testing](../Documentation/Testing.md) methods.

### If adding or updating templates:
* [x] post a screenshot of templates and/or gallery changes
* [x] ensure your template has a corresponding gallery entry in the gallery folder
* [ ] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [x] ensure all steps have meaningful names
* [x] ensure all parameters and grid columns have display names set so they can be localized
* [x] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [x] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [x] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [x] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Comment by rishabhgarg777** [comment]
What is problem in using the same VMList parameters. Even though this have, and VIS ID what problem we faced in using same parameter?

**Comment by rishabhgarg777** [comment]
Lets fix this user behavior, This is not expected, We should have a proper message to land to customer.
image

**Comment by rishabhgarg777** [comment]
When show help is set to "no" then this message should not appear. This might have missed earlier but let's fix this now.

**Comment by adityashukla-msft** [comment]
> When show help is set to "no" then this message should not appear. This might have missed earlier but let's fix this now.

Done.

**Comment by adityashukla-msft** [comment]
> Lets fix this user behavior, This is not expected, We should have a proper message to land to customer. image

Hiding all 4 tiles when no VIS is selected, and instead showing a message bar telling the user to select a VIS.

image

**Review by rishabhgarg777 — APPROVED** [review]

**Pull request merged**
