### PR TITLE
Adding API Security Workbook 

### PR DESCRIPTION
**Pull request by laragoldstein13**
image

## PR Checklist

* [ ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* Provides a security mapping for Microsoft Defender for APIs plan based on the resource telemetry from Azure Resource Graph.

### If adding or updating templates:
* [ ] post a screenshot of templates and/or gallery changes
* [ ] ensure your template has a corresponding gallery entry in the gallery folder
* [ ] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [ ] ensure all steps have meaningful names
* [ ] ensure all parameters and grid columns have display names set so they can be localized
* [ ] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [ ] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [ ] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [ ] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Comment by laragoldstein13** [comment]
If possible, please merge this PR on Sunday 4/23 or Monday 4/24 when Defender for APIs is officially released to public preview.

**Comment by laragoldstein13** [comment]
@gardnerjr would it be possible to approve this today now that Defender for APIs is in public preview?

**Comment by gardnerjr** [comment]
@laragoldstein13 the code is owned by `microsoft/defender-for-cloud-workbooks` team, so someone in that team needs to approve it and merge it, not the workbooks team.

**Comment by laragoldstein13** [comment]
@microsoft/defender-for-cloud-workbooks please merge this PR

**Review by ahmedmasalha — APPROVED** [review]

**Pull request merged**
