### PR TITLE
Single workbook for both SKUs in new format

### PR DESCRIPTION
**Pull request by abshamsft**
## PR Checklist

* [ ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [ ] *if updating templates, it is helpful to post a screenshot of what the changes look like.*
* [ ] *if updating templates, ensure that your parameters and steps have meaningful names.*
* [ ] *if adding new templates, or changing items in a gallery, it's helpful to post a screenshot of what the gallery looks like now*

### CODE REVIEW

**Comment by sayghosh** [comment]
@abshamsft Please add the settings.json for the new workbook added, parallel to the workbook.

**Comment by abshamsft** [comment]
> @abshamsft Please add the settings.json for the new workbook added, parallel to the workbook.

Added settings.json

**Comment by sayghosh** [comment]
@abshamsft One final rename as requested offline. (Sorry missed it first time0

**Comment by abshamsft** [comment]
> @abshamsft One final rename as requested offline. (Sorry missed it first time0

Done

**Pull request merged**
