### PR TITLE
[HANA workbook] GA preparedness

### PR DESCRIPTION
**Pull request by lharcekova**
## PR Checklist

Fixes
- MVCC tab: Not filtering according to selected timeframe, provider, etc..
- System Overview: In the failover scenario for the HA system, the user can see graphs with multiple VMs. Legend needed to make clear why multiple lines are displayed. Secondly, it does not update every second, every min should be changed to
- System Utilization: In a failover scenario we don't show the values when the other VMs took over judging by the times.
- Backup State: Needs to be the required parameter, otherwise it leads to error.

### If adding or updating templates:
* [x] post a screenshot of templates and/or gallery changes
* [x] ensure your template has a corresponding gallery entry in the gallery folder
* [x] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [x] ensure all steps have meaningful names
* [x] ensure all parameters and grid columns have display names set so they can be localized
* [x] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [x] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [x] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [x] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Comment by masree** [comment]
@adityaku-ms please remove "SQL External Monitoring" group as required reviewer as we are not committers on this repo and also do not own HANA workbooks. Probably our team got included by mistake? Please help clarify

**Comment by gardnerjr** [comment]
@masree fyi, that team *is contributors* to this repo as of 2 years ago.  that team owns this path in CODEOWNERS:

/Workbooks/Workloads/SQL/** @microsoft/sqlexternalmonitoring

as of this change:
https://github.com/microsoft/Application-Insights-Workbooks/commit/f62b712295835472915d4d0c328c0e0bfd87f0af

by @[bhsu-ms](https://github.com/microsoft/Application-Insights-Workbooks/commits?author=bhsu-ms)
bhsu-ms committed on Nov 10, 2021

not sure why they were tagged in this PR though?

**Comment by masree** [comment]
> /Workbooks/Workloads/SQL/

Correct, SQL External Monitoring only owns the above folder path you mention and not sure why we got tagged in this PR as it is not related to above path,

**Comment by gardnerjr** [comment]
@masree i was clarifying your comment "as we are not committers on this repo", as you certainly are :)

**Comment by adityaku-ms** [comment]
> @adityaku-ms please remove "SQL External Monitoring" group as required reviewer as we are not committers on this repo and also do not own HANA workbooks. Probably our team got included by mistake? Please help clarify

yeah, 2 teams got included by mistake. I have removed them now

**Pull request merged**
