### PR TITLE
Adding Azure Monitor Logs Dedicated Cluster workbook

### PR DESCRIPTION
**Pull request by Brunoga-MS**
## PR Checklist

* [ ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [ ] Validate your changes using one or more of the [testing](../Documentation/Testing.md) methods.

This workbook will help finding details about workspaces, tiers, pricing tiers current ingestion, estimation of chargeback

### If adding or updating templates:
* [ ] post a screenshot of templates and/or gallery changes
* [ ] ensure your template has a corresponding gallery entry in the gallery folder
* [ ] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [ ] ensure all steps have meaningful names
* [ ] ensure all parameters and grid columns have display names set so they can be localized
* [ ] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [ ] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [ ] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [ ] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Comment by gardnerjr** [comment]
unclear: why are there 3 sub parameters of which 2 are hidden?

image

why not just have one sub parameter that finds all subs that have the resource type you're looking for, like

```
resources
| where type =~ 'microsoft.operationalinsights/clusters'
| distinct subscriptionId
```

if i replace all the other sub parameters with just that one it seems to work fine, but i'm not entirely sure why you did that.

then later there's 10 parameters that do strange things to filter down resources with some really strange queries which seem to all produce the same resource for me for 2-10?  1 is a list, everything else is the same single item?

for me i get errors that i can't query some of the workspaces involved so that's strange as well, so i don't think i can see the *whole* content of the workbook, so i'm not sure the intent of what it is doing, but the fact that it tries to figure out 10 different workspaces that way is strange to me?

**Comment by gardnerjr** [comment]
seeing some screenshots of what it looks like in full action for real users with real access would also be good?

**Comment by Brunoga-MS** [comment]
Hey @gardnerjr ,
the 3 parameters are supposed to relief the customer from the pain of selecting subscription containing the Cluster and the workspaces which might be different. this way they just get all the subscription to which they have access to with no need to select the one containing the cluster. Regarding the parameter, I needed 10 since the cross-resource limit is 100 and we could have up to 1000 workspaces linked to a cluster (if not mistaken, the limit has been recently moved to 7000).

As far as the screenshots go, I can add something or I can demo using a customer env. Up to your choice.

**Comment by Brunoga-MS** [comment]
@gardnerjr : attaching some screenshots. Let me know if there's any other question I did not answer. Thanks.

DedicatedCluster_4
DedicatedCluster_3
DedicatedCluster_2
DedicatedCluster_1
DedicatedCluster_5

**Review by gardnerjr — APPROVED** [review]

**Comment by gardnerjr** [comment]
> @gardnerjr : what is missing to merge?

given that it isn't even running the build validation, i'm presuming it means you are not a member of any of the teams that have write access to the repo?

see the [contributing docs](https://github.com/microsoft/Application-Insights-Workbooks/blob/master/CONTRIBUTING.md#recommended-setup-for-contributing) around joining a team or creating a team

aside: i see this in the "Azure monitor - workspaces" folder and am not 100% sure that's where it should be?  *gallery wise*, azure monitor i get, but i wonder if this template should really be in the `LogAnalytics Workspace` folder to fall under the LA team's ownership?

**Comment by Brunoga-MS** [comment]
Got you ... so far I am only member of microsoft/observabilityagents given my contribution to the 'AMA health' one. I thought about 'Azure Monitor - workspaces' since the cluster embraces more than one workspace and it works more at the Azure Monitor level. Don't you think so? If you agree, could you pls add me to the 'microsoft/azure-monitor-workspaces' group or point me to the proper person to do that?

**Comment by gardnerjr** [comment]
@brunoga-ms you are not a member of https://github.com/orgs/microsoft/teams/observabilityagents, or you would have write access to the repo.  If you get added to that group, you'd be able to complete this PR.

the confusion about that folder, and the azure-monitor-workspaces team is that there is a literal actual resource type called "Azure Monitor Workspaces", which is *not* the same thing as "Log Analytics Workspaces"

**Comment by Brunoga-MS** [comment]
strange thing, since Shayoni granted me that membership. As far as the confusion goes, feel free to advise for the best in term of visibility and context. Do you who can I ask for the right membership? I am going on vacation till the end of August, I will work again on this one once back.

**Comment by gardnerjr** [comment]
> strange thing, since Shayoni granted me that membership. As far as the confusion goes, feel free to advise for the best in term of visibility and context. Do you who can I ask for the right membership? I am going on vacation till the end of August, I will work again on this one once back.

i pinged Shayoni internally, but as i said you can look at the membership of that group and you are not there.  You'd have to talk to the owners of that group if you're contributing for something they intend to own.  Ownership here is tied to who supports these templates once they are released.

**Pull request merged**
