### PR TITLE
Fix dynamic type in Perf

### PR DESCRIPTION
**Pull request by thaitranms**
## PR Checklist

Fix dynamic type error in Perf workbooks:
[perf-workbooks.docx](https://github.com/microsoft/Application-Insights-Workbooks/files/5197808/perf-workbooks.docx)

### CODE REVIEW

**Comment by gardnerjr** [comment]
fyi, you can paste images right into the editor in github, not sure why you created a word doc for the screenshots?

image

**Comment by gardnerjr** [comment]
it also looks like you added some new workbook content without corresponding `settings.json` files?  not sure if that was intentional or copy/paste of files that got added?

**Comment by thaitranms** [comment]
@gardnerjr I did not add any new file. I find that "Workbooks\Virtual Machines - Performance Analysis\Performance Counters (Preview)" does not have settings.json, will add it soon

**Comment by nasundar** [comment]
Perf Counters workbook is broken in your [branch link](https://ms.portal.azure.com/?feature.workbookGalleryBranch=users%2Fthatran%2F7765641_perf_fix_dynamic_type#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/workbooks).

image

image

**Comment by thaitranms** [comment]
@nasundar Fixed the file name
image

**Review by andrewki-msft — APPROVED** [review]

**Pull request merged**
