### PR TITLE
C164292: Fixing indentation to have the content well formatted

### PR DESCRIPTION
**Pull request by v-maudel**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: Missing indentation is not letting the content to render properly

### CODE REVIEW

**Comment by v-maudel** [comment]
Hi @kumarvaranasi, can you please help us by approving and merging/sing in off this PR?
Regards

**Comment by v-maudel** [comment]
#sign-off

**Comment by v-maudel** [comment]
Thanks @kumarvaranasi, although I can't sign it off. Could you please try #sign-off-ces-pm on your side?
Regards

**Comment by v-maudel** [comment]
Thanks @kumarvaranasi, although I can't sign it off. Could you please try #sign-off-ces-pm on your side?
Regards

**Comment by v-maudel** [comment]
Thanks @kumarvaranasi, although I can't sign it off. Could you please try #sign-off-ces-pm on your side?
Regards
CC @gardnerjr

**Comment by v-maudel** [comment]
Hi @kumarvaranasi, @gardnerjr  carmonmills, can you please help by approving and merging this PR?
Regards

**Comment by gardnerjr** [comment]
is this now no longer necessary?

**Comment by gardnerjr** [comment]
is this now no longer necessary given the other PR was completed?

**Comment by gardnerjr** [comment]
@v-maudel is this still necessary?

**Comment by v-maudel** [comment]
Fixed here: https://github.com/microsoft/Application-Insights-Workbooks/pull/589/files

**Pull request closed without merging**
