### PR TITLE
Adding new workbook for Microsoft Entra ID Protection and updated gallery

### PR DESCRIPTION
**Pull request by Corissalea**
…lery

## PR Checklist

* [x] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [x] Validate your changes using one or more of the [testing](../Documentation/Testing.md) methods.

### If adding or updating templates:
* [x] post a screenshot of templates and/or gallery changes
* [x] ensure your template has a corresponding gallery entry in the gallery folder
* [x] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [x] ensure all steps have meaningful names
* [x] ensure all parameters and grid columns have display names set so they can be localized
* [x] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [x] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [x] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [x] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Comment by Corissalea** [comment]
Added new workbook called "Impact analysis of risk-based access policies" and created new folder for Identity Protection related workbook using the updated product name, Microsoft Entra ID Protection: 

Screenshot 2024-01-31 214549

**Review by SarahBar — APPROVED** [review]
Workbook looks good. However, I did spot an apparent typo in the warning at the top of the report. This sentence appears to have an issue: "No policies need to be enabled or in report-only mode." Should the "or" be removed?

**Comment by gardnerjr** [comment]
this should be adding CODEOWNERS info so your team properly owns the folders.

**Review by gardnerjr — APPROVED** [review]
not evaluating *content* of templates, as our team doesn't have access to Entra data.  approving codeowners, etc changes

**Pull request merged**
