### PR TITLE
Changed the queries to use InsightsMetrics for Performance Counter Workbook

### PR DESCRIPTION
**Pull request by rakshith210**

### CODE REVIEW

**Comment by andrewki-msft** [comment]
@rakshith210 would you add some screenshots

**Comment by rakshith210** [comment]
perfCountersWorkbook

**Comment by rakshith210** [comment]
> @rakshith210 would you add some screenshots

Done

**Comment by andrewki-msft** [comment]
Few things, but we can take care of this before the template goes public

- Time range should be set to 3 days, for some reason I'm not seeing any data with 48 hours
- Should be more pre-set counter variety, right now I see a lot of counters being repeated in the 2nd row

**Pull request merged**
