### PR TITLE
Adding code owners for respective metrics workbooks

### PR DESCRIPTION
**Pull request by deveshjagwani**
## PR Checklist

* [ ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [ ] *if updating templates, it is helpful to post a screenshot of what the changes look like.*
* [ ] *if updating templates, ensure that your parameters and steps have meaningful names.*
* [ ] *if adding new templates, or changing items in a gallery, it's helpful to post a screenshot of what the gallery looks like now*

### CODE REVIEW

**Comment by sayghosh** [comment]
@gardnerjr Please help with approval for addition of RP specific owners within Network Insights templates.

**Comment by gardnerjr** [comment]
@sayghosh i don't think this will work as is.  the rules for CODEOWNERS ([see here](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners))

> Order is important; the last matching pattern takes the most precedence. 

i think you'll want to flip the order of your changes, *and* you'll want to copy the owners from the previous line to the new lines and add the new people?  otherwise, the new paths *only* include that one user and our team.  the new paths should include *all* the relevant people who can approve.

**Comment by gardnerjr** [comment]
to verify your changes, the simplest way is this:

https://www.npmjs.com/package/codeowners

install that npm package, then go into the `workbooks/network insights` folder and do `codeowners audit` and it will tell you who is codeowner on each file.

**Comment by deveshjagwani** [comment]
@gardnerjr Changed the order and added initial owners as well to the two new code paths.

**Comment by gardnerjr** [comment]
FYI though, you should really be filling in the PR description with some information about what/why, like the checklist says you should.

**Pull request merged**
