### PR TITLE
Onboard postgresql flexible server

### PR DESCRIPTION
**Pull request by pradeepkintali**
## PR Checklist

* [x] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
Onboard PostgreSQL For Flexible Servers for Workbooks with Overview and Enhanced Metrics.
[Testing URL](https://portal.azure.com/?feature.customportal=false&forceEnableFeatures=Microsoft.DBforPostgreSQL%2FenableWorkbooks&feature.workbookGalleryRedirect=https%3A%2F%2Fprkintworkbooks.blob.core.windows.net%2Fworkbooks%2Fpackage#home)
image
image
image

### If adding or updating templates:
* [x] post a screenshot of templates and/or gallery changes
* [x] ensure your template has a corresponding gallery entry in the gallery folder
* [x] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [x] ensure all steps have meaningful names
* [x] ensure all parameters and grid columns have display names set so they can be localized
* [x] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [x] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [x] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [x] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Review by nasc17 — APPROVED** [review]

**Review by gardnerjr — COMMENTED** [review]
I don't have any resources of the type to verify on, so only really have recommendations from screenshots.

why are you using info boxes as separators/headers?

image

the blue info boxes are generally used to note something important, not just as a divider.  I'd suggest setting titles on individual charts or using more normal header elements in markdown without the blue boxes.

**Comment by gardnerjr** [comment]
Ideally every chart/grid in these templates would have its own title, instead of using info and upsell styled textboxes.  Users are used to seeing those to indicate something out of the ordinary, where here you seem to be using them as titles?

**Review by gardnerjr — APPROVED** [review]
l don't have resources to really test, presume your team has via the instructions here

https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Testing.md

If you didn't already onboard with the form sent via teams, you should also do that as well.

**Comment by pradeepkintali** [comment]
> Ideally every chart/grid in these templates would have its own title, instead of using info and upsell styled textboxes. Users are used to seeing those to indicate something out of the ordinary, where here you seem to be using them as titles?

We want to separate it as sections for example below all metrics belongs to Storage that's why created an Info box as heading. Do you suggest any other control here?

image

**Comment by pradeepkintali** [comment]
> l don't have resources to really test, presume your team has via the instructions here
> 
> https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Testing.md
> 
> If you didn't already onboard with the form sent via teams, you should also do that as well.

Yes, we tested this internally using the private deployment with blob container. And also submitted the form for Team onboarding.

**Comment by pradeepkintali** [comment]
> Ideally every chart/grid in these templates would have its own title, instead of using info and upsell styled textboxes. Users are used to seeing those to indicate something out of the ordinary, where here you seem to be using them as titles?

We have similar Workbooks for MySQL Flexible server which we implemented 1 year back.

**Review by seernu — APPROVED** [review]

**Pull request merged**
