### PR TITLE
Add conditional visibility for the text in Security & Audit Workbook

### PR DESCRIPTION
**Pull request by zishinchua**
## Summary

Add conditional visibility for the text in Security & Audit Workbook so that it does not show up all the time.

## Screenshots

- [ ] If you added a template to a gallery, show a screenshot of it in the gallery view (which verifies its shows up where you expected).

  It is also good to show a screenshot of template content, so people can see what you expect it to look like, compared to what they see when they might run it themselves.

## Validation

- [ ] Validate your changes using one or more of the [testing](https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Testing.md) methods.
  
  Make sure you've tested your template content. Fixing things while in PR is trivial. Hotfixing it later is very expensive; at the current time at least 3 teams are involved in a hotfix!

## Checklist

- [ ] If you are adding a new template, gallery, or folder, add your team and folder/file(s) to the CODEOWNERS file at the root of the repo. CODEOWNERS entries should be teams, not individuals.
      When done correctly, this means that from then on *your* team does reviews of *your* things, not the workbooks team.
- [ ] Ensure all steps in your template have meaningful names.
- [ ] Ensure all parameters and grid columns have display names set so they can be localized.

### CODE REVIEW

**Comment by gardnerjr** [comment]
@zishinchua @nasundar you should also update the `CODEOWNERS` to point at a real github *team* that will own this content, so it isn't only owned by naga?

**Comment by zishinchua** [comment]
> @zishinchua @nasundar you should also update the `CODEOWNERS` to point at a real github _team_ that will own this content, so it isn't only owned by naga?

@gardnerjr I created a new team '[VM Insights Workbook Contributors](https://github.com/orgs/microsoft/teams/vm-insights-workbook-contributors)', but the team does not have access to this repository, and I don't have permission to add it, could you help to add it?

**Review by sarahpeiffer — APPROVED** [review]
lgtm

**Review by deagraw — APPROVED** [review]

**Review by nasundar — APPROVED** [review]

**Review by gardnerjr — APPROVED** [review]
approved for the code owners part.  not entirely sure about the actual change to the workbook, presuming someone from the VMI/CI team has reviewed that?

**Comment by zishinchua** [comment]
> approved for the code owners part. not entirely sure about the actual change to the workbook, presuming someone from the VMI/CI team has reviewed that?

Yes, the change has been reviewed by the VMI UX team members!

**Pull request merged**
