### PR TITLE
Update Account Lockout Query to remove error

### PR DESCRIPTION
**Pull request by zhvolosh**
## PR Checklist

* [X ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
Based on a customer case, a "dynamic expression" error was displaying for the account lockout case. I have updated the query to remove the error.

### If adding or updating templates:
* [ ] post a screenshot of templates and/or gallery changes
* [ ] ensure your template has a corresponding gallery entry in the gallery folder
* [ ] If you are adding a new template, add your team and template/gallery file(s) to the CODEOWNERS file. CODEOWNERS entries should be teams, not individuals
* [ ] ensure all steps have meaningful names
* [ ] ensure all parameters and grid columns have display names set so they can be localized
* [ ] ensure that parameters id values are unique __or they will fail PR validation__ (parameter ids are used for localization)
* [ ] ensure that steps names are unique __or they will fail PR validation__ (step names are used for localization)
* [ ] grep `/subscription/` and ensure that your parameters don't have any hardcoded resourceIds __or they will fail PR validation__
* [ ] remove `fallbackResourceIds` and `fromTemplateId` fields from your template workbook __or they will fail PR validation__

### CODE REVIEW

**Review by SarahBar — CHANGES_REQUESTED** [review]
I'm getting a JSON parsing error when I load this code into a workbook. The error message reads as follows:

> Failed to parse workbook JSON:
> SyntaxError: Unexpected token S in JSON at position 79534
> 
> Please correct the JSON and use 'Apply' to try again.

**Comment by billmath** [comment]
#sign-off

**Comment by zhvolosh** [comment]
Fixed JSON error and tested by pasting in Workbooks.

**Comment by gardnerjr** [comment]
closing ancient uncompleted pull requests

**Pull request closed without merging**
