### PR TITLE
removing categoryResource json - test

### PR DESCRIPTION
**Pull request by MGoedtel**
## PR Checklist

* [ ] Explain your changes, so people looking at the PR know *what* and *why*, the code changes are the *how*.
* [ ] *if updating templates, it is helpful to post a screenshot of what the changes look like.*
* [ ] *if updating templates, ensure that your parameters and steps have meaningful names.*
* [ ] *if adding new templates, ensure that your parameters and columns have display names.*
* [ ] *if adding new templates, or changing items in a gallery, it's helpful to post a screenshot of what the gallery looks like now*

Removing redundant categoryResources.json file from the sub-folder under Azure Monitor - Workspaces to see if it resolves redundancy of category when viewing from AzMon\Workbooks.

### CODE REVIEW

**Comment by MGoedtel** [comment]
- I need to package and upload to my storage blob to test and verify this change I'm testing works.  #please-hold this PR.

**Comment by MGoedtel** [comment]
@yves-chan - I've adjusted strategy after consideration, aligning the parent folder for the workbooks with Azure Monitor agents instead of LA workspace.  This aligns with how it's positioned in the docs and with the service, including future plans around the agent.  I've tested this locally and it works so I'd like your approval to move forward.  As I add new workbooks/features, it makes it easy to keep contained in this "package". #sign-off

**Comment by yves-chan** [comment]
Although this works I still think we should use[ virtual categories](https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Contributing.md#how-to-associate-any-existing-template-to-an-additional-category-in-workbooks)  to solve our folder structure issue
image
I could be wrong here, but theses workbooks don't necessarily need two different categories because the workbook themselves are related to workspaces.

Can we also set isPreview in the settings.json on the older workbook (or alternatively, we can just have an empty gallery array) to hide it from the gallery)?

**Comment by yves-chan** [comment]
Had a quick sync with Matt on teams, in the future there would be a lot of different kinds of Agents, so it makes sense to start making agents it's own category. We've added a deprecated message in the old workbook.

We will add a workbook link inside the old workbook to point users to the new one. This will be done in a different PR

**Pull request merged**
