### PR TITLE
attempting resource id validation

### PR DESCRIPTION
**Pull request by gardnerjr**
this pr should fail to validate because there's a workbook that is failing this validation.

so this proves that the test works, then I can fix the workbook in a different pr, then this should work to validate.

### CODE REVIEW

**Comment by gardnerjr** [comment]
@ericc1103 why didn't this PR run the validation checks? because no json/etc were changed?

**Comment by gardnerjr** [comment]
actually, it looks like the build/validation part isn't running at all, I don't see build/test output on any of the recent PRs

**Comment by gardnerjr** [comment]
would implement part of #124 for resource ids at least

**Comment by ericc1103** [comment]
@gardnerjr  Yours needs to be checked-in in order to be used.

**Comment by gardnerjr** [comment]
@ericc1103 if you have to complete the PR to run the tests, then anyone could actively prevent everyone from completing any PRs by simply creating a test that always fails and completing the PR.  If the tests are modified as part of a PR the PR should run the tests, no?

**Comment by ericc1103** [comment]
You would have to test your PR by running it locally. I won't run in GitHub until it checked in.

**Comment by gardnerjr** [comment]
completing, but there's the possibility this breaks things things the changes to the tests don't get run as part of this PR...

**Pull request merged**
