### PR TITLE
Changed the query in VMSS Perf Analysis to use InsightsMetrics

### PR DESCRIPTION
**Pull request by rakshith210**
Changed the charts in Perf Analysis workbook for VMSS to use InsightsMetrics

image

### CODE REVIEW

**Comment by gardnerjr** [comment]
are those 4 charts always those 4 metrics?  if so, use chart settings to set y axis range 0-100 for the % one, set the y axis units on all of them to the appropriate things?  then the metrics at the bottom, labels on the side will show the right info?

**Comment by gardnerjr** [comment]
also, I've previously suggested making this into tabs so that only the top 10 or top 100 sections are showing, which would prevent some of the queries from running all the time?

**Comment by rakshith210** [comment]
> also, I've previously suggested making this into tabs so that only the top 10 or top 100 sections are showing, which would prevent some of the queries from running all the time?

I made the change to create tabs for top 10 and top 100 sections. Below are the screenshots of the same.

**Comment by rakshith210** [comment]
workbookTopMachines10Tab

workbookTopMachinesTab

**Comment by gardnerjr** [comment]
same comment on the at scale one andrew just did:  you can get rid of the gray divider lines and text inside the top of each tab and get some space back.  the tab control itself now is that divider and text

**Pull request merged**
